# Generated by Django 5.1.6 on 2025-04-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextWordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_word_count', models.IntegerField()),
                ('word_frequencies', models.JSONField()),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='political_culture.texts')),
            ],
        ),
        migrations.AddField(
            model_name='texts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='political_culture.users'),
        ),
    ]
