# Generated by Django 5.1.6 on 2025-04-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='content_description',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
