# Generated by Django 5.1.6 on 2025-05-14 19:01

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('political_culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunks',
            name='vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
