# Generated by Django 5.1.6 on 2025-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('political_culture', '0002_textchunks_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunks',
            name='chunk_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='texts',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='texts',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
