# Generated by Django 5.1.5 on 2025-02-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_esp32data'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp32data',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='esp32data',
            name='temperateure',
            field=models.FloatField(null=True),
        ),
    ]
