# Generated by Django 5.1.5 on 2025-02-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_esp32data_humidity_esp32data_temperateure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32data',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='esp32data',
            name='temperateure',
            field=models.FloatField(),
        ),
    ]
