# Generated by Django 5.1.5 on 2025-02-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_esp32data_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32data',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='esp32data',
            name='temperateure',
            field=models.FloatField(null=True),
        ),
    ]
