# Generated by Django 5.1.5 on 2025-02-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_esp32data_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp32data',
            name='analog_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='esp32data',
            name='temperateure',
            field=models.IntegerField(null=True),
        ),
    ]
