# Generated by Django 5.1.5 on 2025-02-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_alter_esp32data_analog_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esp32data',
            old_name='temperateure',
            new_name='temperature',
        ),
    ]
