# Generated by Django 6.0.5 on 2026-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfflch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionpdf',
            name='search_title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
